version: 2
jobs:
  build:
    docker:
      - image: docker.io/aparcar/openwrt-imagebuilder:x86-64
    steps:
      - run:
          working_directory: /imagebuilder
          name: create image
          command: |
            make image
      - run:
          name: check successful image creation
          command: ls /imagebuilder/bin/targets/x86/64/openwrt-x86-64-generic-rootfs.tar.gz
      - store_artifacts:
          path: /imagebuilder/bin/targets/x86/64/
