version: 2
jobs:
  build:
    docker:
      - image: docker.io/aparcar/openwrt-sdk
    steps:
      - run:
          working_directory: /sdk
          name: update feeds
          command: |
            ./scripts/feeds update base
            echo "CONFIG_DEVEL=y" > .config
            echo "CONFIG_SRC_TREE_OVERRIDE=y" >> .config
            make defconfig
      - run:
          name: setup firewall.git
          command: |
            git clone https://git.openwrt.org/project/firewall3.git fw3
            ln -s ./fw3/.git/ /sdk/feeds/base/package/network/config/firewall/git-src
      - run:
          working_directory: /sdk
          name: install & compile firewall package
          command: |
            ./scripts/feeds install firewall
            make package/firewall/{clean,compile} -j$(nproc) || make package/firewall/compile V=s
      - store_artifacts:
          path: /sdk/bin/packages/x86_64/base/firewall*
