version: 2
jobs:
  build:
    docker:
      - image: docker.io/aparcar/openwrt:master
        command: /sbin/init
    steps:
      - run: while [ "$(cat /proc/1/cmdline)" != "/sbin/procd" ]; do sleep 2; done
      - run: ps
