version: 2
jobs:
  build:
    docker:
      - image: docker.io/aparcar/openwrt:master
        command: /sbin/init
    steps:
      - run: ps
      - run: sleep 1
      - run: ps
      - run: sleep 5
      - run: ps
