version: 2
jobs:
  build:
    docker:
      - image: docker.io/apracar/openwrt-sdk
    steps:
      - run:
          working_directory: /sdk
          name: update feeds
          run: ./scripts/feeds update base
      - run:
          name: setup firewall.git
          command: |
            git clone https://git.openwrt.org/project/firewall3.git fw3
            echo "CONFIG_DEVEL=y" > .config
            echo "CONFIG_SRC_TREE_OVERRIDE=y" >> .config
            make defconfig
            ln -s ./fw3/.git/ /sdk/feeds/base/package/network/config/firewall/git-src
      - run:
          working_directory: /sdk
          name: install firewall package
          run: ./scripts/feeds install firewall
      - run:
          working_directory: /sdk
          name: compile firewall package
          run: make package/firewall/{clean,compile} -j$(nproc) || make package/firewall/compile V=s
