version: 2
jobs:
  build:
    docker:
      - image: docker.io/aparcar/openwrt-sdk
    steps:
      - restore_cache:
          keys:
            - firewall
      - run:
          working_directory: /sdk
          name: update feeds
          command: |
            ./scripts/feeds update base
            echo "CONFIG_DEVEL=y" > .config
            echo "CONFIG_SRC_TREE_OVERRIDE=y" >> .config
            make defconfig
      - run:
          name: setup firewall.git
          command: |
            git clone https://git.openwrt.org/project/firewall3.git fw3
            ln -s ./fw3/.git/ /sdk/feeds/base/package/network/config/firewall/git-src
      - run:
          working_directory: /sdk
          name: install & compile firewall package
          command: |
            ./scripts/feeds install firewall
            make package/firewall/{clean,compile} -j$(nproc) || make package/firewall/compile V=s
      - store_artifacts:
          path: /sdk/bin/packages/x86_64/base/
      - save_cache:
          key: firewall
          paths:
            - "/sdk"
  test:
    docker:
      - image: docker.io/aparcar/openwrt
        command: /sbin/init
    steps:
      - run: sleep 10
      - run:
          name: install firewall package
          command: |
            opkg update
            opkg install --force-reinstall /sdk/bin/packages/x86_64/base/firewall*
      - run:
          name: try to break firewall
          command: |
            i=0
            while true; do iptables -N unitttest; iptables -A unittest -j ACCEPT -d 127.0.0.1; done &
            while [ "$(iptables -w -L OUTPUT | wc -l)" -gt 2 -a $i -lt 1000 ]; do fw3 reload; i=$((i+1)); done
            [ $i -lt 1000 ] && exit 1
