version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: curl -s "$BASE_URL/$ROOTFS_URL" -o rootfs.tar.gz
     - run: docker build -t $DOCKER_USER/openwrt:$CIRCLE_BRANCH .
     - run: docker push $DOCKER_USER/openwrt:$CIRCLE_BRANCH

